# Site settings
title: Trevor Renshaw's CV
description: Trevor Renshaw's CV
favicon: /assets/img/avatar.JPG
baseurl: https://trevren11.github.io/
url: https://trevren11.github.io/
rss_url: /pages/atom.xml
google_analytics: UA-81737450-1

# Build settings
markdown: kramdown

exclude: [vendor]

# Author settings
author:
  name: Trevor Renshaw
  title: Software Engineer
  address: Provo, Utah
  email: trevor.renshaw@gmail.com
  link:
  weibo:
  github: trevren11
  linkedin: TrevorRenshaw
  # twitter: trevren11
  gavatar: /resumecard/assets/img/avatar.JPG
  stackoverflow:
#  stackoverflow: 4582127
  workHistory:
    - work1:
      company: Instructure
      location: Holladay, Utah
      title: Software Engineer Intern in Test
      started: 2016
      duration: (2016 - 2016)
      description: <p> Automated tests for Android, iOS and web using Espresso, EarlGrey and Ruby. <p> Manually regressed 1200+ test cases. <p> Designed and coded open source ruby gem
    - work2:
      company: Brigham Young University
      location: Provo, Utah
      title: Computer Programmer
      started: 2014
      duration: (2014 - Present)
      description: Part of a team that worked on language learning software. Vocal recognition in the browser. Built an inventory website from the ground up and help manage a proprietary video streaming service.
    - work3:
      company: Freelance Developer
      location: Provo, Utah
      title: Website Designer
      started: 2015
      duration: (2015 - Present)
      description: Build professional websites for various clients. Past clients/projects include making a booking and reservation website for the largest log cabin in the US a landing page for a professional wrestler a reception rental website and a landing page for a clothing store.
    - work4:
      company: Entrepreneur
      location: Provo, Utah
      title: Owner
      started: 2014
      duration: (2014 - Present)
      description: I have bought and sold several websites and Android apps, netting me over $4,500. I am currently working on several Android application ideas, the current focus being a dinner planning app that integrates Firebase for authentication, database, analytics and crash/bug reporting. I have one Android app currently on the Play store with several others made.
    - work5:
      company: Vantage Controls
      location: Orem, Utah
      title: Driver Developer Intern
      started: 2015
      duration: (2015 - 2015)
      description: Developed and tested drivers for luxury home automation system. Programmed in PAWN/Small. Designed exception handling concept.
    - work6:
      company: EdgeCreek
      location: Orem, Utah
      title: Accountant
      started: 2014
      duration: (2014 - 2014)
      description: Managed the accounts for ~15 properties as well as the personal finances of the billionaire CEO. Accounts payable and credit card responsibilities.
    - work7:
      company: Costco Wholesale
      location: Des Moines, Iowa
      title: Membership
      started: 2010
      duration: (2010 - 2011)
      description: Managed returns, processed credit card signups for new and existing members.

  educationHistory:
    - education1:
      organization: Brigham Young University
      location: Provo, Utah
      degree: Bachelor
      major: Computer Science - With Honors
      started: 2011
      duration: (2011 - 2017)
      description: Data Structures, Digital Systems, Digital Logic, Probability Theory, Circuits, CAD

  languages:
    - language1:
      name: English
      proficiency: Native
    - language2:
      name: Spanish
      proficiency: Professional
    - language3:
      name: Italian
      proficiency: Limit
    - language4:
      name: French
      proficiency: Limit

  programmingSkills:
    - skill1:
      name: HTML5
      percentage: 80%
    - skill2:
      name: JavaScript/jQuery/nodeJS
      percentage: 75%
    - skill3:
      name: C++
      percentage: 70%
    - skill4:
      name: CSS3/SCSS
      percentage: 80%
    - skill5:
      name: Linux
      percentage: 80%
    - skill6:
      name: GitHub
      percentage: 80%
    - skill7:
      name: Ruby
      percentage: 50%
    - skill8:
      name: PHP
      percentage: 50%
    - skill9:
      name: Java
      percentage: 40%
    - skill10:
      name: PostgreSQL
      percentage: 60%
    - skill11:
      name: AngularJS
      percentage: 30%
    - skill12:
      name: MySQL/SQL/MongoDB/NoSQL
      percentage: 60%
    - skill13:
      name: XML
      percentage: 50%
    - skill14:
      name: Shell Scripting
      percentage: 65%
    - skill15:
      name: Bootstrap
      percentage: 40%
      # - skill16:
      # name: Bootstrap
      # percentage: 40%
      # - skill17:
      # name: Bootstrap
      # percentage: 40%
      # - skill18:
      # name: Bootstrap
      # percentage: 40%
      # - skill19:
      # name: Bootstrap
      # percentage: 40%

      # PAWN
      # MatLab
      # Redis security
      # SCRUM/Agile workflow

      # Awards Eagle Scout
      # Organizations
      # Chile
